### ISSUE TITLE
WAVEFORM_MAX_STEP

### ISSUE THREAD

**Issue by boltonfxs** [lfc7/TAP-tempo-LFO#1]
Hi, I was trying to probe the code and I have the "WAVEFORM_MAX_STEP" undeclared error.

**Comment by lfc7** [comment]
Hi , my bad, files uploaded was not up to date, re-try a complete download.
Lookup table for LFO waves, has been decrease to 256 steps (arduino is not fast enought).
A new ver. for teensy 3.6 (really really faster) is becoming soon  

thanx

**Comment by boltonfxs** [comment]
The code its working! thank you! im going to probe in a protoboard!
